const data = [
    {
      courseCode: "ML101",
      name: "Machine Learning",
      shortName: "ML",
      credits: 3,
      type: "THEORY",
      department: "CSE",
      semester: "3-2",
      regulation: "NRIA 20",
      category: { isLab: false },
    },
    {
      courseCode: "CD101",
      name: "Compiler Design",
      shortName: "CD",
      credits: 3,
      type: "THEORY",
      department: "CSE",
      semester: "3-2",
      regulation: "NRIA 20",
      category: { isLab: false },
    },
    {
      courseCode: "CNS101",
      name: "Cryptography and Network Security",
      shortName: "CNS",
      credits: 3,
      type: "THEORY",
      department: "CSE",
      semester: "3-2",
      regulation: "NRIA 20",
      category: { isLab: false },
    },
    {
      courseCode: "OE201",
      name: "OE2: Image Processing",
      shortName: "IP",
      credits: 3,
      type: "THEORY",
      department: "CSE",
      semester: "3-2",
      regulation: "NRIA 20",
      category: { isLab: false },
    },
    {
      courseCode: "PE201",
      name: "PE2: Big Data Analytics",
      shortName: "BDA",
      credits: 3,
      type: "THEORY",
      department: "CSE",
      semester: "3-2",
      regulation: "NRIA 20",
      category: { isLab: false },
    },
    {
      courseCode: "ML102",
      name: "Machine Learning Lab",
      shortName: "ML Lab",
      credits: 2,
      type: "LAB",
      department: "CSE",
      semester: "3-2",
      regulation: "NRIA 20",
      category: { isLab: true },
    },
    {
      courseCode: "CD102",
      name: "Compiler Design Lab",
      shortName: "CD Lab",
      credits: 2,
      type: "LAB",
      department: "CSE",
      semester: "3-2",
      regulation: "NRIA 20",
      category: { isLab: true },
    },
    {
      courseCode: "RP101",
      name: "R Programming Lab",
      shortName: "RPL",
      credits: 2,
      type: "LAB",
      department: "CSE",
      semester: "3-2",
      regulation: "NRIA 20",
      category: { isLab: true },
    },
    {
      courseCode: "MSTL101",
      name: "Mean Stack Technology Lab",
      shortName: "MST Lab",
      credits: 2,
      type: "LAB",
      department: "CSE",
      semester: "3-2",
      regulation: "NRIA 20",
      category: { isLab: true },
    },
    {
      courseCode: "ES201",
      name: "Employability Skills-2",
      shortName: "ES2",
      credits: 3,
      type: "THEORY",
      department: "CSE",
      semester: "3-2",
      regulation: "NRIA 20",
      category: { isLab: false },
    },
    {
      courseCode: "CPT101",
      name: "CPT",
      shortName: "CPT",
      credits: 2,
      type: "LAB",
      department: "CSE",
      semester: "3-2",
      regulation: "NRIA 20",
      category: { isLab: true },
    },
  ];
  
  module.exports = { data };
  