const data = [
  {
    courseCode: "20A3105401",
    name: "Artificial Intelligence",
    shortName: "AI",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "3-1",
    regulation: "NRIA 20",
    category: { isLab: false },
  },
  {
    courseCode: "20A3105402",
    name: "Computer Networks",
    shortName: "CN",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "3-1",
    regulation: "NRIA 20",
    category: { isLab: false },
  },
  {
    courseCode: "20A3105403",
    name: "Design and Analysis of Algorithms",
    shortName: "DAA",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "3-1",
    regulation: "NRIA 20",
    category: { isLab: false },
  },
  {
    courseCode: "28A3104601",
    name: "Microprocessor and Applications",
    shortName: "MPA",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "3-1",
    regulation: "NRIA 20",
    category: { isLab: false },
  },
  {
    courseCode: "20A1105491",
    name: "Computer Networks Lab",
    shortName: "CN Lab",
    credits: 2,
    type: "LAB",
    department: "CSE",
    semester: "3-1",
    regulation: "NRIA 20",
    category: { isLab: true },
  },
  {
    courseCode: "20A3105492",
    name: "AI Programming Lab",
    shortName: "AI Lab",
    credits: 2,
    type: "LAB",
    department: "CSE",
    semester: "3-1",
    regulation: "NRIA 20",
    category: { isLab: true },
  },
  {
    courseCode: "20A3105991",
    name: "DevOps Lab",
    shortName: "DevOps Lab",
    credits: 2,
    type: "LAB",
    department: "CSE",
    semester: "3-1",
    regulation: "NRIA 20",
    category: { isLab: true },
  },
  {
    courseCode: "20A3205403",
    name: "Machine Learning",
    shortName: "ML",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "3-2",
    regulation: "NRIA 20",
    category: { isLab: false },
  },
  {
    courseCode: "20A3205402",
    name: "Compiler Design",
    shortName: "CD",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "3-2",
    regulation: "NRIA 20",
    category: { isLab: false },
  },
  {
    courseCode: "20A3205401",
    name: "Cryptography and Network Security",
    shortName: "CNS",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "3-2",
    regulation: "NRIA 20",
    category: { isLab: false },
  },
  {
    courseCode: "20A3201604 / 20A3204602",
    name: "Elements of Civil Engineering / Image Processing",
    shortName: "EOCE / IP",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "3-2",
    regulation: "NRIA 20",
    category: { isLab: false },
  },
  {
    courseCode: "20A3205513",
    name: "Big Data Analytics",
    shortName: "BDA",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "3-2",
    regulation: "NRIA 20",
    category: { isLab: false },
  },
  {
    courseCode: "20A3205491",
    name: "Machine Learning Lab",
    shortName: "ML Lab",
    credits: 2,
    type: "LAB",
    department: "CSE",
    semester: "3-2",
    regulation: "NRIA 20",
    category: { isLab: true },
  },
  {
    courseCode: "20A3205492",
    name: "R Programming Lab",
    shortName: "R Prog Lab",
    credits: 2,
    type: "LAB",
    department: "CSE",
    semester: "3-2",
    regulation: "NRIA 20",
    category: { isLab: true },
  },
  {
    courseCode: "20A3205493",
    name: "Compiler Design Lab",
    shortName: "CD Lab",
    credits: 2,
    type: "LAB",
    department: "CSE",
    semester: "3-2",
    regulation: "NRIA 20",
    category: { isLab: true },
  },
  {
    courseCode: "20A3205991",
    name: "Mean Stack Technologies Lab",
    shortName: "MST Lab",
    credits: 2,
    type: "LAB",
    department: "CSE",
    semester: "3-2",
    regulation: "NRIA 20",
    category: { isLab: true },
  },
  {
    courseCode: "20A3205801",
    name: "Employability Skills - 2",
    shortName: "Emply Skills-II",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "3-2",
    regulation: "NRIA 20",
    category: { isLab: false },
  },
  {
    courseCode: "20A4105511",
    name: "Data Science",
    shortName: "Data Scie",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "4-1",
    regulation: "NRIA 20",
    category: { isLab: false },
  },
  {
    courseCode: "20A4105521",
    name: "Deep Learning and Its Applications",
    shortName: "DL&IA",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "4-1",
    regulation: "NRIA 20",
    category: { isLab: false },
  },
  {
    courseCode: "20A4105535",
    name: "Data Visualization Techniques",
    shortName: "DVT",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "4-1",
    regulation: "NRIA 20",
    category: { isLab: false },
  },
  {
    courseCode: "20A4103609",
    name: "Additive Manufacturing",
    shortName: "AM",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "4-1",
    regulation: "NRIA 20",
    category: { isLab: false },
  },
  {
    courseCode: "20A4101611",
    name: "Engineering Project Management",
    shortName: "EPM",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "4-1",
    regulation: "NRIA 20",
    category: { isLab: false },
  },
  {
    courseCode: "20A4100101",
    name: "Universal Human Values",
    shortName: "UHV",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "4-1",
    regulation: "NRIA 20",
    category: { isLab: false },
  },
  {
    courseCode: "20A4100801",
    name: "Functional English for 21st Century Learning",
    shortName: "FEL for 21st CL",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "4-1",
    regulation: "NRIA 20",
    category: { isLab: false },
  },
  {
    courseCode: "20A4105991",
    name: "Data Visualization Lab",
    shortName: "DV Lab",
    credits: 2,
    type: "LAB",
    department: "CSE",
    semester: "4-1",
    regulation: "NRIA 20",
    category: { isLab: true },
  },
  {
    courseCode: "23A2100205",
    name: "Discrete Mathematics and Graph Theory",
    shortName: "DMGT",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "2-1",
    regulation: "NRIA 23",
    category: { isLab: false },
  },
  {
    courseCode: "23A2100102",
    name: "Universal Human Values Understanding Harmony",
    shortName: "UHV-UH",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "2-1",
    regulation: "NRIA 23",
    category: { isLab: false },
  },
  {
    courseCode: "23A2105301",
    name: "Digital Logic and Computer Organization",
    shortName: "DLCO",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "2-1",
    regulation: "NRIA 23",
    category: { isLab: false },
  },
  {
    courseCode: "23A2105401",
    name: "Database Management Systems",
    shortName: "DBMS",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "2-1",
    regulation: "NRIA 23",
    category: { isLab: false },
  },
  {
    courseCode: "23A2105402",
    name: "Object Oriented Programming Through Java",
    shortName: "OOPS THR JAVA",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "2-1",
    regulation: "NRIA 23",
    category: { isLab: false },
  },
  {
    courseCode: "23A2105491",
    name: "Database Management Systems Lab",
    shortName: "DBMS LAB",
    credits: 2,
    type: "LAB",
    department: "CSE",
    semester: "2-1",
    regulation: "NRIA 23",
    category: { isLab: true },
  },
  {
    courseCode: "23A2105492",
    name: "Object Oriented Programming Through Java Lab",
    shortName: "OOPS THR JAVA L",
    credits: 2,
    type: "LAB",
    department: "CSE",
    semester: "2-1",
    regulation: "NRIA 23",
    category: { isLab: true },
  },
  {
    courseCode: "23A2105991",
    name: "Python Programming",
    shortName: "PYTHON PROG",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "2-1",
    regulation: "NRIA 23",
    category: { isLab: false },
  },
  {
    courseCode: "23A2100801",
    name: "Constitution of India",
    shortName: "COI",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "2-1",
    regulation: "NRIA 23",
    category: { isLab: false },
  },
  {
    courseCode: "23A2200103",
    name: "Optimization Techniques",
    shortName: "OT",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "2-2",
    regulation: "NRIA 23",
    category: { isLab: false },
  },
  {
    courseCode: "23A2200202",
    name: "Probability and Statistics",
    shortName: "P&S",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "2-2",
    regulation: "NRIA 23",
    category: { isLab: false },
  },
  {
    courseCode: "23A2205401",
    name: "Operating Systems",
    shortName: "OS",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "2-2",
    regulation: "NRIA 23",
    category: { isLab: false },
  },
  {
    courseCode: "23A2205402",
    name: "Advanced Data Structures and Algorithm Analysis",
    shortName: "ADSAA",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "2-2",
    regulation: "NRIA 23",
    category: { isLab: false },
  },
  {
    courseCode: "23A2205403",
    name: "Artificial Intelligence",
    shortName: "AI",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "2-2",
    regulation: "NRIA 23",
    category: { isLab: false },
  },
  {
    courseCode: "23A2205491",
    name: "Operating Systems Lab",
    shortName: "OS LAB",
    credits: 2,
    type: "LAB",
    department: "CSE",
    semester: "2-2",
    regulation: "NRIA 23",
    category: { isLab: true },
  },
  {
    courseCode: "23A2205492",
    name: "Advanced Data Structures and Algorithm Analysis Lab",
    shortName: "ADSAA LAB",
    credits: 2,
    type: "LAB",
    department: "CSE",
    semester: "2-2",
    regulation: "NRIA 23",
    category: { isLab: true },
  },
  {
    courseCode: "23A2205991",
    name: "Full Stack Development- I",
    shortName: "FSD-I",
    credits: 2,
    type: "LAB",
    department: "CSE",
    semester: "2-2",
    regulation: "NRIA 23",
    category: { isLab: true },
  },
  {
    courseCode: "23A2200291",
    name: "Design Thinking and Innovation",
    shortName: "DT&I",
    credits: 3,
    type: "THEORY",
    department: "CSE",
    semester: "2-2",
    regulation: "NRIA 23",
    category: { isLab: false },
  },
];

module.exports = { data };
